name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build Website
        run: npm run build

      - name: Deploy to Production
        run: |
          # Add commands to deploy to production here
          # For example, you might use SCP, FTP, or other deployment methods
          # It's essential to secure your deployment credentials/secrets
          # You can use GitHub Secrets to store sensitive information.
